name = "debesteaitools"
compatibility_date = "2026-03-27"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true
preview_urls = true

routes = [
  { pattern = "debesteaitools.nl", custom_domain = true },
  { pattern = "www.debesteaitools.nl", custom_domain = true },
]

[assets]
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true
