/**
 * AI Tools Domain Model
 *
 * Two-layer architecture:
 * - ToolContent: editorial data (managed via CMS / JSON, never overwritten by ETL)
 * - ToolStats:   dynamic data (overwritten every newsflux run)
 *
 * The merge of both produces a full Tool DTO for rendering.
 */

// ============================================
// ENUMS
// ============================================

/** Lifecycle phase of a trend or tool (from newsflux classify_phase) */
export type TrendPhase =
  | 'weak_signal'
  | 'emerging'
  | 'accelerating'
  | 'peaking'
  | 'sustained'
  | 'declining'
  | 'faded';

/** Trend direction (from newsflux determine_trend_direction) */
export type TrendDirection = 'rising' | 'stable' | 'declining';

/** Source types tracked by newsflux SmartSourceScanner */
export type SourceType =
  | 'twitter'
  | 'reddit'
  | 'articles'
  | 'linkedin'
  | 'github'
  | 'hackernews'
  | 'arxiv'
  | 'bluesky';

/** Tool lifecycle status (from status_classifier.py) */
export type ToolStatus =
  | 'active'
  | 'discontinued'
  | 'acquired'
  | 'open_sourced'
  | 'relaunched'
  | 'funding';

/** Tool categories — matches both newsflux ai_tool_taxonomy.py and our categories.ts */
export type ToolCategory =
  | 'chatbots'
  | 'coding'
  | 'automation'
  | 'image'
  | 'video'
  | 'audio'
  | 'search'
  | 'productivity'
  | 'infrastructure';

/** Business functions for the /zakelijk niche page */
export type BusinessFunctionKey =
  | 'marketing'
  | 'sales'
  | 'klantenservice'
  | 'development'
  | 'data'
  | 'operations'
  | 'hr'
  | 'finance';

/** Pricing model */
export type PricingModel = 'free' | 'freemium' | 'paid' | 'enterprise';

/** Difficulty level for end users */
export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced';

// ============================================
// CONTENT LAYER (editorial — never overwritten by ETL)
// ============================================

/** Tool content managed editorially (JSON files in src/content/tools/) */
export interface ToolContent {
  /** Display name */
  name: string;
  /** Primary category */
  category: ToolCategory;
  /** Official website */
  websiteUrl: string;
  /** One-liner in Dutch (from taxonomy) */
  shortDescription: string;
  /** Extended description (from LLM enrichment, editorially approved) */
  longDescription?: string;
  /** Who benefits most (from enrichment) */
  bestFor?: string;
  /** Concrete use cases */
  useCases?: string[];
  /** Strengths */
  strengths?: string[];
  /** Limitations */
  limitations?: string[];
  /** Pricing info in Dutch */
  pricing?: string;
  /** Is open source */
  openSource?: boolean;
  /** Pricing model classification */
  pricingModel: PricingModel;
  /** Difficulty for end users */
  difficulty: DifficultyLevel;
  /** Tags for filtering */
  tags: string[];
  /** Business functions for /zakelijk page */
  businessFunctions: BusinessFunctionKey[];
  /** Draft flag */
  draft: boolean;
}

// ============================================
// STATS LAYER (dynamic — overwritten every newsflux run)
// ============================================

/** Daily history point for sparklines */
export interface HistoryPoint {
  date: string;
  mentions: number;
}

/** A source article reference */
export interface SourceArticle {
  title: string;
  url: string;
  source: string;
  /** Dutch title (generated by enrichment LLM, optional) */
  title_nl?: string;
  /** Dutch one-line summary (generated by enrichment LLM, optional) */
  summary_nl?: string;
}

/** GitHub trending repo linked to a tool */
export interface GitHubRepo {
  repo: string;
  stars_today: number;
  description: string;
}

/** Stats for a single tool (from ai_tools_radar.json) */
export interface ToolStats {
  slug: string;
  buzz_score: number;
  trend_direction: TrendDirection;
  mentions: number;
  velocity: number;
  source_count: number;
  sources: SourceType[];
  phase: TrendPhase;
  days_active: number;
  history: HistoryPoint[];
  github_stars: number;
  github_repos: number;
  github_top_repos: GitHubRepo[];
  reddit_posts: number;
  product_hunt_mentions: number;
  newsletter_mentions: number;
  source_articles: SourceArticle[];

  // --- v3: already computed in newsflux, not yet exported ---

  /** 2nd derivative of velocity — early signal for accelerating tools */
  acceleration?: number;
  /** 0.0–1.0 ratio of expert (HN/ArXiv) vs total mentions */
  expert_ratio?: number;
  /** Historical peak mention count */
  peak_mentions?: number;
  /** ISO date of first mention (for "Nieuw" badge accuracy) */
  first_seen?: string;
  /** ISO date of most recent mention (for staleness detection) */
  last_seen?: string;
  /** Related search terms from trendsnapshots */
  related_terms?: string[];
  /** Per-source mention breakdown (e.g. { twitter: 120, reddit: 45 }) */
  source_breakdown?: Record<string, number>;

  // --- v3: new data sources (future pipelines) ---

  /** Weekly npm download count (from npm_pypi_fetcher.py) */
  npm_downloads?: number;
  /** Weekly PyPI download count (from npm_pypi_fetcher.py) */
  pypi_downloads?: number;

  // --- v3: status classification (from status_classifier.py) ---

  /** Lifecycle status beyond phase — discontinued, acquired, etc. */
  status?: ToolStatus;
  /** Confidence of the status classification (0.0–1.0) */
  status_confidence?: number;
  /** ISO date when status change was detected */
  status_changed_at?: string;
}

/** Top-level radar JSON shape (from newsflux generate_ai_tools_radar.py) */
export interface ToolsRadarData {
  generated_at: string;
  window_days: number;
  total_tools_tracked: number;
  categories: Record<string, { name: string; icon: string; color: string; description_nl: string; count: number }>;
  tools: (ToolStats & {
    name: string;
    category: string;
    description_nl: string;
    url: string;
    enrichment: ToolEnrichment | null;
  })[];
  sections: {
    meest_besproken: string[];
    stijgers: string[];
    nieuw: string[];
    github_hot: string[];
    product_hunt_hot: string[];
    /** v3: expert-curated top picks (high expert_ratio + buzz) */
    expert_picks?: string[];
  };
  github_trending_repos: GitHubTrendingRepo[];
  product_hunt_discoveries: ProductHuntDiscovery[];
  /** v3: recent tool status events (from status_classifier.py) */
  status_events?: ToolStatusEvent[];
}

/** A detected tool status change event */
export interface ToolStatusEvent {
  tool_slug: string;
  event_type: ToolStatus;
  detected_date: string;
  confidence: number;
  severity: 'low' | 'medium' | 'high';
  source_count: number;
  confirmed?: boolean;
  evidence?: { title: string; url?: string }[];
}

/** Enrichment data cached per tool (from enrich_tools_radar.py) */
export interface ToolEnrichment {
  description_long_nl: string;
  best_for_nl: string;
  use_cases: string[];
  strengths: string[];
  limitations: string[];
  pricing_nl: string;
  open_source: boolean;
  enriched_at: string;
  slug: string;
  model: string;
  /** Dutch how-to / getting-started tip (optional, from enrichment) */
  quick_start_nl?: string;
}

/** GitHub trending repo (standalone, not linked to a specific tool) */
export interface GitHubTrendingRepo {
  repo: string;
  description: string;
  language: string;
  stars_period: number;
  total_stars: number;
  terms: string[];
}

/** Product Hunt discovery */
export interface ProductHuntDiscovery {
  name: string;
  url: string;
  date: string;
}

// ============================================
// MERGED DTO (content + stats combined for rendering)
// ============================================

/** Full tool object for rendering — merge of ToolContent + ToolStats */
export interface Tool extends ToolContent {
  /** URL-safe slug derived from filename (hyphens, no spaces) */
  slug: string;
  /** Stats from newsflux (undefined if no stats available yet) */
  stats?: ToolStats;
}
