import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { glob } from 'astro/loaders';
import { toolContentSchema } from './lib/tools-schema';
import { nieuwsCategorySchema } from './lib/nieuws-schema';

const tools = defineCollection({
  loader: glob({ base: './src/content/tools', pattern: '**/*.json' }),
  schema: toolContentSchema,
});

const nieuws = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/nieuws' }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    publishedAt: z.coerce.date(),
    updatedAt: z.coerce.date().optional(),
    author: z.string().default('Redactie'),
    category: nieuwsCategorySchema.default('nieuws'),
    tags: z.array(z.string()).default([]),
    toolSlug: z.string().optional(),
    featured: z.boolean().default(false),
    draft: z.boolean().default(false),
    heroImage: z.string().optional(),
    readingTime: z.number().optional(),
    keyTakeaways: z.array(z.string()).optional(),
    faq: z.array(z.object({
      q: z.string(),
      a: z.string(),
    })).optional(),
  }),
});

// Daily AI tools digest generated by the newsflux pipeline
// (src/digest/tools_digest.py). Minimal schema on purpose: each digest
// is a short markdown file rendered from pre-computed reports.
// Note: README.md is excluded so the pipeline docs file doesn't show up
// as a content entry.
const digest = defineCollection({
  loader: glob({
    pattern: ['**/*.md', '!README.md'],
    base: './src/content/digest',
  }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    // Mirror the `date` / `timeSlot` naming used by hetlaatsteainieuws.nl
    // so downstream tooling can share helpers across both sites.
    date: z.coerce.date(),
    timeSlot: z.string().default('tools-digest'),
    author: z.string().default('debesteaitools.nl Redactie'),
    tags: z.array(z.string()).default([]),
    topics: z.array(z.string()).optional(),
    heroImage: z.string().optional(),
    draft: z.boolean().default(false),
    // Pipeline stats (all optional; the generator fills what it knows)
    totalAnalyzed: z.number().optional(),
    itemsSelected: z.number().optional(),
    categoriesCount: z.number().optional(),
    featured: z.array(z.string()).optional(),
  }),
});

export const collections = { tools, nieuws, digest };
