import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { glob } from 'astro/loaders';
import { toolContentSchema } from './lib/tools-schema';
import { nieuwsCategorySchema } from './lib/nieuws-schema';

const tools = defineCollection({
  loader: glob({ base: './src/content/tools', pattern: '**/*.json' }),
  schema: toolContentSchema,
});

const nieuws = defineCollection({
  // Exclude `*.social.md`: losse social-post captions, bewust naast het
  // artikel-bestand in src/content/nieuws/social/ geparkeerd (geen artikel-schema).
  loader: glob({ pattern: ['**/*.md', '!**/*.social.md'], base: './src/content/nieuws' }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    publishedAt: z.coerce.date(),
    updatedAt: z.coerce.date().optional(),
    author: z.string().default('Redactie'),
    category: nieuwsCategorySchema.default('nieuws'),
    tags: z.array(z.string()).default([]),
    toolSlug: z.string().optional(),
    featured: z.boolean().default(false),
    draft: z.boolean().default(false),
    heroImage: z.string().optional(),
    readingTime: z.number().optional(),
    keyTakeaways: z.array(z.string()).optional(),
    faq: z.array(z.object({
      q: z.string(),
      a: z.string(),
    })).optional(),
  }),
});

// Daily AI tools digest generated by the newsflux pipeline
// (src/digest/tools_digest.py).
//
// The generator emits structured arrays in frontmatter (launches, updates,
// deep_dives, key_signals) so the Astro page can render cards + badges
// directly instead of parsing free-form markdown. The markdown body only
// contains the editorial note. Older digests (pre-redesign) have neither
// the arrays nor the counts — the detail page falls back to rendering the
// markdown body in that case, so both schemas stay renderable.
const launchEntrySchema = z.object({
  name: z.string(),
  summary_nl: z.string().default(''),
  url: z.string(),
  source_type: z.string().default('other'),
  source_label: z.string().default(''),
  confidence: z.enum(['hoog', 'medium', 'laag']).default('medium'),
  favicon: z.string().optional(),
});

const updateEntrySchema = z.object({
  tool_name: z.string(),
  tool_slug: z.string().optional(),
  feature_title: z.string().default(''),
  summary_nl: z.string().default(''),
  impact: z.enum(['hoog', 'medium', 'laag']).default('medium'),
  url: z.string(),
  source_type: z.string().default('other'),
  source_label: z.string().default(''),
  confidence: z.enum(['hoog', 'medium', 'laag']).default('medium'),
  platforms: z.array(z.string()).default([]),
  key: z.string().optional(),
});

const deepDiveEntrySchema = z.object({
  title: z.string(),
  summary_nl: z.string().default(''),
  url: z.string(),
  tool: z.string().optional(),
  trend_phase: z.string().optional(),
  score: z.number().optional(),
});

const digest = defineCollection({
  loader: glob({
    pattern: ['**/*.md', '!README.md'],
    base: './src/content/digest',
  }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    // Mirror the `date` / `timeSlot` naming used by hetlaatsteainieuws.nl
    // so downstream tooling can share helpers across both sites.
    date: z.coerce.date(),
    timeSlot: z.string().default('tools-digest'),
    slotLabel: z.string().optional(),
    author: z.string().default('debesteaitools.nl Redactie'),
    tags: z.array(z.string()).default([]),
    topics: z.array(z.string()).optional(),
    heroImage: z.string().optional(),
    draft: z.boolean().default(false),
    // Pipeline stats (all optional; the generator fills what it knows)
    totalAnalyzed: z.number().optional(),
    itemsSelected: z.number().optional(),
    categoriesCount: z.number().optional(),
    featured: z.array(z.string()).optional(),
    // Structured sections (new — optional so old digests still validate)
    launches: z.array(launchEntrySchema).optional(),
    updates: z.array(updateEntrySchema).optional(),
    deepDives: z.array(deepDiveEntrySchema).optional(),
    keySignals: z.array(z.string()).optional(),
    launchesCount: z.number().optional(),
    updatesCount: z.number().optional(),
    deepDivesCount: z.number().optional(),
  }),
});

export const collections = { tools, nieuws, digest };
